name: Feature 请求
description: 提出新能力或增强建议
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: 背景与动机
      description: 为什么需要这个功能？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 方案描述
      description: 描述你建议的行为、接口与边界
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 你考虑过哪些替代方案？
  - type: textarea
    id: impact
    attributes:
      label: 影响评估
      description: 对协议/兼容性/运维的影响
