name: Task 任务
description: 记录工程任务（重构/文档/运维）
labels: [task]
body:
  - type: textarea
    id: objective
    attributes:
      label: 目标
      description: 这项任务要达成什么结果？
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: 范围
      description: 涉及模块与不在范围内的内容
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      description: 可观测、可验证的完成条件
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: 备注
      description: 关联 Issue/PR、风险或依赖
