from __future__ import annotations

from typing import Final, Set


STATUS_SUCCESS: Final = "success"
STATUS_FAILED: Final = "failed"
STATUS_CANCELED: Final = "canceled"
STATUS_TIMEOUT: Final = "timeout"
STATUS_PARTIAL: Final = "partial"

STATUS_RUNNING: Final = "running"
STATUS_PENDING: Final = "pending"
STATUS_DISPATCHED: Final = "dispatched"

STATUS_PLANNED: Final = "planned"
STATUS_REVIEW: Final = "review"
STATUS_BLOCKED: Final = "blocked"

TOOL_RESULT_STATUSES: Final = (
    STATUS_SUCCESS,
    STATUS_FAILED,
    STATUS_CANCELED,
    STATUS_TIMEOUT,
    STATUS_PARTIAL,
)
TOOL_RESULT_STATUS_SET: Final[Set[str]] = set(TOOL_RESULT_STATUSES)

BATCH_STATUSES: Final = (
    STATUS_RUNNING,
    STATUS_SUCCESS,
    STATUS_FAILED,
    STATUS_TIMEOUT,
    STATUS_PARTIAL,
)
BATCH_STATUS_SET: Final[Set[str]] = set(BATCH_STATUSES)

BATCH_TASK_STATUSES: Final = (
    STATUS_PENDING,
    STATUS_DISPATCHED,
    STATUS_SUCCESS,
    STATUS_FAILED,
    STATUS_CANCELED,
    STATUS_TIMEOUT,
    STATUS_PARTIAL,
)
BATCH_TASK_STATUS_SET: Final[Set[str]] = set(BATCH_TASK_STATUSES)

BATCH_TASK_TERMINAL_SET: Final[Set[str]] = {
    STATUS_SUCCESS,
    STATUS_FAILED,
    STATUS_CANCELED,
    STATUS_TIMEOUT,
    STATUS_PARTIAL,
}
BATCH_TASK_FAILURE_SET: Final[Set[str]] = {
    STATUS_FAILED,
    STATUS_CANCELED,
    STATUS_TIMEOUT,
}

PLAN_MODULE_STATUSES: Final = (
    STATUS_PLANNED,
    STATUS_RUNNING,
    STATUS_REVIEW,
    STATUS_BLOCKED,
    STATUS_SUCCESS,
    STATUS_FAILED,
    STATUS_CANCELED,
    STATUS_TIMEOUT,
    STATUS_PARTIAL,
)
PLAN_MODULE_STATUS_SET: Final[Set[str]] = set(PLAN_MODULE_STATUSES)
