from __future__ import annotations

ACK_STATUS_ACCEPTED = "accepted"
ACK_STATUS_BUSY = "busy"
ACK_STATUS_REJECTED = "rejected"
ACK_STATUS_ERROR = "error"

ERROR_PROTOCOL_VIOLATION = "protocol_violation"
ERROR_RECURSION_DEPTH_EXCEEDED = "recursion_depth_exceeded"
ERROR_AGENT_BUSY = "agent_busy"
ERROR_STORAGE_ERROR = "storage_error"
ERROR_INTERNAL_ERROR = "internal_error"

ACK_STATUS_SET = {
    ACK_STATUS_ACCEPTED,
    ACK_STATUS_BUSY,
    ACK_STATUS_REJECTED,
    ACK_STATUS_ERROR,
}

ERROR_CODE_SET = {
    ERROR_PROTOCOL_VIOLATION,
    ERROR_RECURSION_DEPTH_EXCEEDED,
    ERROR_AGENT_BUSY,
    ERROR_STORAGE_ERROR,
    ERROR_INTERNAL_ERROR,
}
