#!/usr/bin/env python
"""Import YAML Profile into card-box-cg and persist it as a sys.profile card in CardBox.

Usage:
  uv run python scripts/import_profile_cardbox.py \
      --yaml resources/profiles/sample_partner.yaml \
      --project-id demo_project \
      --box-name partner_demo_v1

Outputs created card_id and box_id (UUID).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from datetime import datetime, UTC

from core.app_config import load_app_config, config_to_dict

from core.utp_protocol import Card, JsonContent
from infra.cardbox_client import CardBoxClient

try:
    import yaml
except ImportError as e:  # pragma: no cover - runtime dependency hint
    print("PyYAML is missing. Install it with `uv add pyyaml` or `pip install pyyaml`.", file=sys.stderr)
    raise


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Import YAML profile into card-box-cg")
    parser.add_argument("--yaml", dest="yaml_path", required=True, help="Profile YAML file path")
    parser.add_argument("--project-id", dest="project_id", default="public", help="Project/tenant ID for the cardbox repository")
    parser.add_argument("--box-name", dest="box_name", default=None, help="[deprecated] CardBox name; box_id is auto-generated by backend as UUID")
    parser.add_argument("--config", dest="config_path", default="config.toml", help="Path to config file (for cardbox DSN)")
    return parser.parse_args()


def main():
    args = parse_args()
    yaml_path = Path(args.yaml_path)
    if not yaml_path.exists():
        raise FileNotFoundError(f"YAML file not found: {yaml_path}")

    profile_data = yaml.safe_load(yaml_path.read_text())
    if not isinstance(profile_data, dict):
        raise ValueError("YAML root must be a mapping")

    profile_id = profile_data.get("profile_id") or yaml_path.stem

    cfg = config_to_dict(load_app_config(Path(args.config_path)))
    cardbox_cfg = cfg.get("cardbox", {})
    cardbox = CardBoxClient(config=cardbox_cfg)

    # Build sys.profile card
    card_id = f"card_{profile_id}"
    card = Card(
        card_id=card_id,
        project_id=args.project_id,
        type="sys.profile",
        content=JsonContent(data=profile_data),
        created_at=datetime.now(UTC),
        author_id="system",
        metadata={
            "name": profile_data.get("name"),
            "worker_target": profile_data.get("worker_target"),
            "tags": profile_data.get("tags"),
            "profile_id": profile_id,
            "type": "sys.profile",
        },
    )

    # Persist card and CardBox
    import asyncio

    async def run():
        await cardbox.init()
        await cardbox.save_card(card)
        box_id = await cardbox.save_box([card.card_id], project_id=args.project_id)
        return card.card_id, box_id

    card_id_out, box_id_out = asyncio.run(run())
    print(f"Created profile card: {card_id_out}")
    print(f"Created profile box_id: {box_id_out}")


if __name__ == "__main__":
    main()
